name: On PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint-PR-title:
    name: 'lint PR title to follow "type(scope): description" format'
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
            Supported types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
  add_label_on_PR:
    runs-on: ubuntu-latest
    steps:
      - name: Add label on PR
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disable-releaser: true
          disable-autolabeler: false
