name: On PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  create_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Add label on PR
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disable-releaser: true
          disable-autolabeler: false
